apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: sample-api-config
    namespace: deep-k8s
    literals:
      - APP_MESSAGE=hello-from-base
generatorOptions:
  labels:
    app.kubernetes.io/name: sample-api
    app.kubernetes.io/part-of: deep-k8s-lab
