CREATE TABLE inventory (
    sku VARCHAR(50) PRIMARY KEY,
    stock INT NOT NULL CHECK (stock >= 0),
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL UNIQUE,
    customer_id VARCHAR(100) NOT NULL,
    total DECIMAL(19,2) NOT NULL CHECK (total >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_orders_customer_created ON orders(customer_id, created_at DESC, id DESC);
