apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-api.fullname" . }}
  labels:
    {{- include "sample-api.labels" . | nindent 4 }}
data:
  APP_MESSAGE: {{ .Values.app.message | quote }}
