apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pdb.yaml
  - hpa.yaml
  - network-policies.yaml
patches:
  - path: api-patch.yaml
images:
  - name: visits-api
    newName: registry.example.com/team/visits-api
    newTag: 1.0.0

