export const LANGUAGE_KEY = 'ccar-learning-language-v1'

export const ui = {
  vi: {
    language: 'Ngôn ngữ', navLabel: 'Không gian học', learn: 'Học bài', practice: 'Luyện tập', reference: 'Tra cứu',
    progress: 'Tiến độ học', topics: 'chuyên đề', tip: 'Mẹo hôm nay', tipText: 'Học nguyên lý, đừng học vị trí đáp án.',
    search: 'Tìm chuyên đề, nguyên tắc...', verified: 'Dữ liệu đã đối chiếu', theme: 'Đổi giao diện', close: 'Đóng',
    heroEyebrow: 'LỘ TRÌNH TƯƠNG TÁC · TIẾNG VIỆT', heroTitleA: 'Làm chủ cách', heroTitleB: 'AI Agent', heroTitleC: 'vận hành.', heroAlt: 'Minh họa lõi AI kết nối code, dữ liệu, công cụ, bộ nhớ, an toàn và nhiều agent',
    heroBody: 'Từ context, tool use đến multi-agent — hiểu sâu 12 nguyên lý cốt lõi để tự tin chinh phục toàn bộ 162 câu hỏi.',
    start: 'Bắt đầu học', roadmap: 'Xem lộ trình', structuredFrom: 'Được cấu trúc từ đề gốc', checkedAll: 'Mọi đáp án đã được đối chiếu 162/162',
    stats: ['câu hỏi được bao phủ', 'chuyên đề cốt lõi', 'chế độ học tập'], curriculum: 'CURRICULUM / 12 MODULES',
    mapTitle: 'Bản đồ kiến thức', mapBody: 'Đi từ nền tảng đến tư duy thiết kế hệ thống đáng tin cậy.', completed: 'đã hoàn thành',
    done: 'Đã học', explore: 'Khám phá chuyên đề', minutes: 'phút', noResult: 'Không tìm thấy chuyên đề',
    noResultBody: 'Thử từ khóa “context”, “tool” hoặc “safety”.', masterTitle: 'Mô hình suy luận.\nHệ thống bảo đảm.',
    masterBody: 'Cho model đủ context và giao diện rõ để suy luận. Dùng schema để định hình dữ liệu. Dùng code, hook và backend để bảo đảm điều không được phép sai.',
    markDone: 'Đánh dấu đã học', markedDone: 'Đã hoàn thành', readMinutes: 'phút đọc', easy: 'GIẢI THÍCH DỄ HIỂU',
    principles: 'Những nguyên tắc cần nhớ', example: 'VÍ DỤ CỤ THỂ', conclusion: 'KẾT LUẬN', traps: 'BẪY THƯỜNG GẶP',
    trapsTitle: 'Vì sao các hướng khác dễ sai?', selfCheck: 'TỰ KIỂM TRA', showAnswer: 'Xem giải thích', hideAnswer: 'Ẩn đáp án',
    previous: 'Bài trước', next: 'Bài tiếp theo', key: 'CHÌA KHÓA LÀM BÀI', atlas: 'KEYWORD ATLAS',
    atlasTitle: 'Từng khái niệm hoạt động ra sao?', atlasBody: 'Đọc flow từ trái sang phải. Mỗi ô là một trạng thái hoặc hành động trong hệ thống.',
    deep: '5-DOMAIN DEEP DIVE', deepTitle: 'Kiến thức bổ sung sau đối chiếu', deepBody: 'Click để mở từng mục kiến thức bổ sung.',
    practical: 'ÁP DỤNG THỰC TẾ', practicalTitle: 'Dùng keyword nào, vào lúc nào?', practicalBody: 'Đối chiếu tín hiệu trong công việc với hành động phù hợp.',
    situation: 'TRƯỜNG HỢP', action: 'NÊN LÀM', result: 'VÍ DỤ KẾT QUẢ', decision: 'QUY TẮC RA QUYẾT ĐỊNH',
    practiceKicker: 'ACTIVE RECALL', practiceTitle: 'Luyện tập theo nguyên lý', practiceBody: '12 câu đại diện cho 12 chuyên đề cốt lõi.',
    score: 'Điểm hiện tại', question: 'CÂU', correct: 'CHÍNH XÁC', incorrect: 'CHƯA ĐÚNG', seeResult: 'Xem kết quả', nextQuestion: 'Câu tiếp theo',
    resultKicker: 'KẾT QUẢ LUYỆN TẬP', resultHigh: 'Xuất sắc — bạn đã nắm rất chắc!', resultMid: 'Rất tốt — chỉ còn vài điểm cần ôn.',
    resultLow: 'Khởi đầu tốt — hãy xem lại bài học.', resultBody: (pct) => `Bạn trả lời đúng ${pct}%. Hãy dùng giải thích sau mỗi câu để tìm nguyên nhân gốc.`, retry: 'Làm lại',
    referenceKicker: 'QUICK REFERENCE', referenceTitle: 'La bàn chọn đáp án', referenceBody: 'Nhận diện cặp nguyên lý ẩn sau mỗi tình huống trước khi nhìn đáp án.',
    coverage: 'DOMAIN COVERAGE', coverageTitle: '64/64 sections đã đối chiếu', coverageBody: 'Nội dung mới được bổ sung vào lesson hiện có, không tạo curriculum trùng lặp.',
    related: 'lesson liên quan', answerIndex: 'ANSWER INDEX', checkQuestion: 'Kiểm tra một câu', checkBody: 'Nhập số từ 1 đến 162. Chỉ xem sau khi bạn đã tự suy luận.',
    questionNumber: 'Số câu', check: 'Kiểm tra', invalid: 'Vui lòng nhập số câu từ 1 đến 162.', correctAnswer: 'Đáp án đúng',
    fiveTraps: '5 BẪY PHẢI TRÁNH', trapHeadline: 'Đáp án nghe “toàn diện” chưa chắc đúng.',
    referenceTraps: ['Đọc tất cả file thay vì lần theo quan hệ code.', 'Retry mọi lỗi thay vì phân loại transient/permanent.', 'Spawn subagent cho cả câu hỏi đơn giản.', 'Tóm tắt toàn bộ và làm mất fact chính xác.', 'Dùng prompt để “bảo đảm” chính sách an toàn.'],
    footer: 'Nội dung dựa trên BAI_HOC_CCAR_F_FOUNDATIONS.md', footerChecked: '162/162 đã đối chiếu',
  },
  en: {
    language: 'Language', navLabel: 'Learning space', learn: 'Learn', practice: 'Practice', reference: 'Reference',
    progress: 'Learning progress', topics: 'topics', tip: 'Today’s tip', tipText: 'Learn the principle, not the answer position.',
    search: 'Search topics and principles...', verified: 'Content verified', theme: 'Toggle theme', close: 'Close',
    heroEyebrow: 'INTERACTIVE ROADMAP · ENGLISH', heroTitleA: 'Master how', heroTitleB: 'AI Agents', heroTitleC: 'work.', heroAlt: 'AI core connected to code, data, tools, memory, safety, and multiple agents',
    heroBody: 'From context and tool use to multi-agent systems — master 12 core principles behind all 162 questions.',
    start: 'Start learning', roadmap: 'View roadmap', structuredFrom: 'Structured from the original quiz', checkedAll: 'All 162 answers have been cross-checked',
    stats: ['questions covered', 'core topics', 'learning modes'], curriculum: 'CURRICULUM / 12 MODULES',
    mapTitle: 'Knowledge roadmap', mapBody: 'Move from first principles to reliable system design.', completed: 'completed',
    done: 'Completed', explore: 'Explore lesson', minutes: 'min', noResult: 'No lesson found', noResultBody: 'Try “context”, “tool”, or “safety”.',
    masterTitle: 'Models reason.\nSystems guarantee.', masterBody: 'Give the model enough context and a clear interface to reason. Use schemas to shape data, and code, hooks, or backends to enforce anything that must not fail.',
    markDone: 'Mark complete', markedDone: 'Completed', readMinutes: 'min read', easy: 'BEGINNER EXPLANATION', principles: 'Principles to remember',
    example: 'WORKED EXAMPLE', conclusion: 'CONCLUSION', traps: 'COMMON TRAPS', trapsTitle: 'Why do the other approaches fail?', selfCheck: 'SELF-CHECK',
    showAnswer: 'Show explanation', hideAnswer: 'Hide answer', previous: 'Previous lesson', next: 'Next lesson', key: 'EXAM KEY',
    atlas: 'CONCEPT FLOW', atlasTitle: 'How do these ideas work in practice?', atlasBody: 'Use the detailed English guide below to follow each concept from signal to decision.',
    deep: 'ENGLISH DEEP DIVE', deepTitle: 'Complete lesson in English', deepBody: 'This section comes from the verified English study guide in the repository.',
    practical: 'REAL-WORLD USE', practicalTitle: 'When should you apply this lesson?', practicalBody: 'Match the signal in your work to a proportionate action.',
    situation: 'SITUATION', action: 'BEST ACTION', result: 'EXPECTED RESULT', decision: 'DECISION RULE',
    practiceKicker: 'ACTIVE RECALL', practiceTitle: 'Practice the principles', practiceBody: '12 questions representing the 12 core topics.', score: 'Current score', question: 'QUESTION',
    correct: 'CORRECT', incorrect: 'NOT QUITE', seeResult: 'See results', nextQuestion: 'Next question', resultKicker: 'PRACTICE RESULT',
    resultHigh: 'Excellent — you have a strong grasp!', resultMid: 'Very good — only a few gaps remain.', resultLow: 'Good start — review the lessons and try again.',
    resultBody: (pct) => `You answered ${pct}% correctly. Use each explanation to identify the underlying principle.`, retry: 'Try again',
    referenceKicker: 'QUICK REFERENCE', referenceTitle: 'Answer-selection compass', referenceBody: 'Identify the principle hidden in each scenario before looking at the answer.',
    coverage: 'DOMAIN COVERAGE', coverageTitle: '64/64 sections cross-checked', coverageBody: 'New material was merged into existing lessons without duplicating the curriculum.',
    related: 'related lessons', answerIndex: 'ANSWER INDEX', checkQuestion: 'Check one question', checkBody: 'Enter a number from 1 to 162. Look only after reasoning it through.',
    questionNumber: 'Question number', check: 'Check', invalid: 'Please enter a question number from 1 to 162.', correctAnswer: 'Correct answer',
    fiveTraps: '5 TRAPS TO AVOID', trapHeadline: 'A “comprehensive” answer is not always correct.',
    referenceTraps: ['Reading every file instead of following code relationships.', 'Retrying every error instead of classifying it.', 'Spawning a subagent for a simple factual question.', 'Summarizing everything and losing exact facts.', 'Using a prompt to “guarantee” a safety policy.'],
    footer: 'Content based on CCAR_F_FOUNDATIONS_STUDY_GUIDE_EN.md', footerChecked: '162/162 verified',
  },
}

export const chapterEn = {
  'agent-loop': { title: 'How does an agent work?', eyebrow: 'Foundations', summary: 'Understand the reason–act loop and why an API does not remember by itself.', intro: 'An agent observes a request, selects a tool, reads the result, and decides what to do next. Every API call only knows what that request includes.', principles: [['Context is working memory', 'The model knows only the prompt, messages, and tool results in the current request.'], ['Tools enable action', 'Describing an action is not the same as executing it; the matching tool must exist.'], ['The orchestrator runs the loop', 'The application executes tools, returns results, and checks terminal states.']], callout: 'If the application does not resend prior messages, the model forgets them even for the same user.' },
  'code-exploration': { title: 'Explore a codebase effectively', eyebrow: 'Developer workflow', summary: 'Search broadly with patterns, read narrowly along evidence, and revise the plan as you learn.', intro: 'In a large codebase, reading everything wastes context and hides execution relationships. Start with a distinctive signal, then follow imports, callers, interfaces, and tests.', principles: [['Glob finds paths', 'Use filename or path patterns to map the repository.'], ['Grep finds content', 'Search errors, imports, function names, and risky patterns.'], ['Read for context', 'Read only the files and regions narrowed by search.'], ['Follow aliases', 'Inspect wrappers and search every exported name before removing an API.']], callout: 'Entry point → import/call chain → interface → implementation → tests.' },
  workflow: { title: 'Plan, Execute, Resume & Fork', eyebrow: 'Ways of working', summary: 'Execute small tasks directly, plan broad changes, and fork independent alternatives.', intro: 'The working mode should match uncertainty and blast radius. Sessions preserve earlier work; forks preserve the same starting point without mixing alternatives.', principles: [['Direct execution', 'Use for small, clear, local changes or a bug with a precise stack trace.'], ['Plan mode', 'Use for breaking migrations, broad changes, or open-ended requests.'], ['Resume with an update', 'Continue the old session but identify code that changed and must be reread.'], ['Fork a session', 'Create independent branches when comparing strategies from the same context.']], callout: 'The greater uncertainty × blast radius, the greater the need for exploration and planning.' },
  context: { title: 'Manage context & memory', eyebrow: 'Memory', summary: 'Separate durable facts, summarized history, recent verbatim turns, and bounded retrieval.', intro: 'Context contains more than chat: prompts, tool definitions, and retrieval all consume tokens. Keep the right information in the right representation for the right duration.', principles: [['Structured facts', 'Store current preferences, allergies, measurements, and world rules as explicit state.'], ['Progressive summaries', 'Compress old decisions without changing their meaning.'], ['Recent verbatim turns', 'Keep exact recent exchanges for the active issue.'], ['Bounded retrieval', 'Retain only the retrieval results that still matter.']], callout: 'More available context does not make old and new preferences unambiguous.' },
  extraction: { title: 'Structured extraction', eyebrow: 'Data', summary: 'Distinguish valid JSON, schema compliance, and semantic correctness.', intro: 'Structured output removes formatting failures, not semantic mistakes. Reliable extraction needs a realistic schema, business validation, and calibrated human review.', principles: [['Syntax', 'The JSON parses and follows the requested output mechanism.'], ['Schema', 'Fields, types, enums, required values, null, and other match reality.'], ['Semantics', 'Values mean what the source means and pass domain checks.'], ['Human review', 'Calibrate confidence by field and segment, including high-confidence audits.']], callout: 'Schemas shape data; examples teach interpretation; validation catches remaining mistakes.' },
  'tool-design': { title: 'Design Tools & MCP', eyebrow: 'Interfaces', summary: 'Clear descriptions, narrow schemas, and a small decision space improve tool use.', intro: 'A tool is an API for the model. Its name, description, parameters, and output directly affect whether the model selects and calls it correctly.', principles: [['Instructional descriptions', 'State when to use it, when not to, and how it differs from similar tools.'], ['Split by intent', 'Different operations and required fields deserve separate tools.'], ['Merge overlap', 'Combine competing tools with the same intent or atomicity requirement.'], ['Canonical IDs', 'Search returns stable IDs; mutations accept IDs instead of ambiguous names.']], callout: 'Different intent or required fields → split. Same intent, overlap, or atomicity → merge.' },
  errors: { title: 'Output & error handling', eyebrow: 'Reliability', summary: 'Retry transient failures in the tool and return structured permanent errors to the agent.', intro: '“Operation failed” gives the agent no recovery path. Errors should identify their class, retryability, cause, and reasonable next action.', principles: [['Transient', 'Retry timeouts, 503s, and network failures with backoff inside the tool.'], ['Permanent', 'Return validation, permission, and business-rule metadata immediately.'], ['Correct MCP layer', 'Protocol faults are JSON-RPC errors; backend failures are tool results with isError.'], ['Concise output', 'Return relevant fields, IDs, cursors, and impact rather than long prose.']], callout: 'Recovery needs both what happened and what can be done next.' },
  safety: { title: 'Safety & enforcement', eyebrow: 'Guardrails', summary: 'Anything that must not fail belongs in backend code, hooks, or orchestration.', intro: 'A prompt guides model behavior; it is not a security boundary. Money limits, destructive confirmations, and terminal outcomes must be enforced architecturally.', principles: [['Backend policy', 'Amounts over the threshold become pending approval regardless of model output.'], ['Preview token', 'Preview returns impact and a one-time token required by execute.'], ['Blocking hooks', 'Intercept calls beyond authority and route them to human review.'], ['Terminal guarantee', 'Inspect every exit path and escalate unresolved work.']], callout: 'Guarantee, tamper-proof, and cannot bypass usually imply code enforcement—not a stronger prompt.' },
  'multi-agent': { title: 'Orchestrate multiple agents', eyebrow: 'Orchestration', summary: 'The coordinator passes state, chooses the decomposition, and preserves source lineage.', intro: 'A subagent does not automatically see another agent’s output. The coordinator must transmit results or references and choose parallel, sequential, dynamic, or fast-path execution.', principles: [['Parallel', 'Run independent tasks concurrently and fan their results in.'], ['Sequential', 'Chain tasks when later work depends on earlier output.'], ['Dynamic routing', 'Route by complexity and keep simple factual work on a fast path.'], ['Source lineage', 'Keep source metadata attached to claims through the final report.']], callout: 'Agent definitions are not enough: the coordinator must also be allowed to delegate.' },
  conversation: { title: 'Conversation & escalation', eyebrow: 'Experience', summary: 'Ask fewer high-value questions, use reversible assumptions, and hand off structured state.', intro: 'Good assistance balances initiative and safety. Do not interrogate before every action, but confirm choices that are costly or irreversible.', principles: [['Transparent assumptions', 'Use context to proceed, state assumptions, and let the user correct them.'], ['One purposeful question', 'Ask only what materially changes the action.'], ['Structured handoff', 'Include customer, issue, evidence, status, and next action.'], ['System prompt', 'Define durable persona and behavior at the system level.']], callout: 'Escalate on request, beyond authority, or when meaningful progress is no longer possible.' },
  quality: { title: 'Evaluation & code review', eyebrow: 'Quality', summary: 'Separate discovery from filtering, inspect beyond the diff, and use examples and tests as feedback.', intro: 'Precision and recall trade off. A strong reviewer searches broadly first, validates evidence, then applies a separate reporting threshold.', principles: [['Coverage stage', 'Find plausible issues and attach confidence and severity.'], ['Filter stage', 'Use a separate threshold to control false positives.'], ['Agentic review', 'Use repository tools to inspect callers and unchanged dependencies.'], ['Fresh perspective', 'Independent review reduces anchoring on the implementation session.']], callout: 'Few-shot examples define the bug boundary better than a generic request to be careful.' },
  cost: { title: 'Cost, latency & exam strategy', eyebrow: 'Summary', summary: 'Match SLA, fast paths, batching, pagination, and execution limits to the actual job.', intro: 'The best design is not only technically correct; it matches SLA and cost. Batch is cheaper but slower, subagents add latency, and excess context can overwhelm.', principles: [['Batch by SLA', 'Use it only when a result delayed up to 24 hours remains useful.'], ['Fast path', 'Simple factual questions do not need the full pipeline.'], ['Direct limits', 'Use max-turns and max-budget-usd to cap each invocation.'], ['Find the root cause', 'Reject answers that read, retry, spawn, or summarize everything.']], callout: 'Missing structure → schema; missing fact → null/retrieve; guarantee → code enforcement.' },
}

export const applicationsEn = {
  'agent-loop': [['Live account data', 'Call a read tool and return its result to the model', 'The answer reflects the current order state.'], ['Multi-step action', 'Let the orchestrator continue until a terminal state', 'The model can inspect each tool result before deciding.'], ['New API request', 'Resend the required history or structured state', 'The model retains the relevant facts.']],
  'code-exploration': [['Unknown production error', 'Grep the distinctive error, then follow callers', 'The investigation adapts to real evidence.'], ['Removing an API', 'Find wrappers and every alias before editing', 'Hidden consumers are not broken.'], ['Large legacy repo', 'Map high-risk entry points first', 'Context is spent on relevant files.']],
  workflow: [['One-line local fix', 'Execute directly and verify', 'Low ceremony, fast feedback.'], ['Breaking migration', 'Explore impact, write a plan, then implement in checkpoints', 'Cross-module risk stays visible.'], ['Two architecture options', 'Resume the research and fork two branches', 'Each option remains independent.']],
  context: [['User changes a preference', 'Update one current-preferences object', 'Old statements no longer compete.'], ['Long support thread', 'Keep facts structured, summarize the past, preserve recent turns', 'Exact active details survive compression.'], ['Repeated retrieval', 'Replace stale RAG results with the latest relevant set', 'Retrieved text does not crowd out reasoning.']],
  extraction: [['Invoice extraction', 'Use a realistic schema plus calculated checks', 'Line items can be verified against totals.'], ['Missing source value', 'Return null or unclear instead of guessing', 'Absence remains distinguishable from zero.'], ['Automated pipeline', 'Calibrate confidence by field and audit samples', 'Human review targets actual risk.']],
  'tool-design': [['Refund versus cancellation', 'Use separate tools with separate required fields', 'The model cannot mix incompatible parameters.'], ['Overlapping credit tools', 'Merge the shared intent into one atomic operation', 'No competition or race condition.'], ['Selecting a record', 'Search first, then mutate by canonical ID', 'Duplicate names do not cause the wrong update.']],
  errors: [['External 503', 'Retry with exponential backoff inside the tool', 'The agent sees only the final meaningful outcome.'], ['Validation failure', 'Return structured, non-retryable metadata', 'The agent asks for the missing field once.'], ['Large result set', 'Return a cursor and concise records', 'The agent paginates without flooding context.']],
  safety: [['Refund over a limit', 'Enforce pending approval in backend code', 'A prompt injection cannot bypass policy.'], ['Destructive operation', 'Require preview plus a one-time confirmation token', 'The user confirms the exact impact.'], ['Unresolved exit', 'Check every terminal state in the orchestrator', 'The case escalates instead of silently ending.']],
  'multi-agent': [['Independent research streams', 'Run agents in parallel and fan in results', 'Latency approaches the slowest branch, not their sum.'], ['Draft depends on research', 'Chain research → synthesis', 'The writer receives explicit evidence.'], ['Mixed complexity traffic', 'Route simple queries to a fast path', 'Easy work avoids orchestration overhead.']],
  conversation: [['Clear, reversible request', 'Proceed with a stated assumption', 'The user can correct it without losing progress.'], ['Irreversible choice', 'Ask one focused clarification', 'The answer changes the action safely.'], ['Human escalation', 'Send a structured handoff', 'The user does not repeat the story.']],
  quality: [['Bug discovery', 'Optimize recall first, then filter findings', 'Potential races are investigated before reporting.'], ['API-changing PR', 'Inspect callers outside the diff', 'Unchanged consumers using the old contract are found.'], ['Generated tests', 'Provide criteria and labeled examples', 'Tests assert behavior rather than merely “not throwing”.']],
  cost: [['Monthly archival report', 'Use batch because the SLA is loose', 'High throughput at lower cost.'], ['Urgent exception alert', 'Use a real-time request path', 'The 30-minute SLA is preserved.'], ['Large agentic review', 'Set turn and cost budgets', 'One invocation cannot loop indefinitely.']],
}

export const applicationDecisionEn = {
  'agent-loop': 'Need current or external state → use a tool. Need another reasoning step → return the tool result and continue the loop.',
  'code-exploration': 'Unknown path → search and adapt. Known local path → read narrowly and verify.', workflow: 'Small + clear → execute. Broad + uncertain → explore and plan. Competing approaches → fork.',
  context: 'Exact durable fact → structured state. Old discussion → summary. Active issue → recent verbatim turns.', extraction: 'Structure → schema. Meaning → examples and validation. Uncertainty → null, confidence, and review.',
  'tool-design': 'Different intent/required fields → split. Same intent/overlap/atomicity → merge.', errors: 'Transient → retry internally. Permanent → stop and return actionable metadata.',
  safety: 'If it must be impossible to bypass, enforce it outside the model.', 'multi-agent': 'Independent → parallel. Dependent → sequential. Simple → fast path.',
  conversation: 'Proceed on reversible assumptions; clarify or escalate when the decision is irreversible or beyond authority.', quality: 'Search broadly for recall, validate evidence, then threshold for precision.',
  cost: 'Value decays quickly → real time. Up to 24 hours is acceptable → batch. Every production loop → explicit limits.',
}

export const quizEn = [
  { q: 'A 500 error appears intermittently in a 200+ file codebase. What is the best decomposition?', options: ['Split into four fixed layers', 'Read all code first', 'Create subtasks dynamically from discoveries', 'Only grep error handlers'], answer: 2, why: 'When the error path is unknown, the investigation must adapt to new evidence.' },
  { q: 'The model forgets terminology from the previous turn. What is the most likely cause?', options: ['The model is too small', 'Message history was not sent again', 'The system prompt is too short', 'MCP memory is mandatory'], answer: 1, why: 'The API is stateless; the application must resend the required history.' },
  { q: 'Two refactoring strategies must evolve independently from the same earlier analysis. What should you do?', options: ['Develop both sequentially in one thread', 'Start two empty sessions', 'Fork the session into two branches', 'Only save the transcript'], answer: 2, why: 'Forking preserves the shared starting context without anchoring the alternatives to each other.' },
  { q: 'JSON matches the schema, but line items do not sum to the grand total. What is the best improvement?', options: ['Change the model', 'Remove the total', 'Add a calculated total and consistency flag', 'Retry forever'], answer: 2, why: 'This is semantic validation: compare extracted values with an independently calculated field.' },
  { q: 'Cardio and strength tools often receive the wrong parameter combinations. What should you do?', options: ['Only lengthen the description', 'Split them by domain and intent', 'Add every field to one tool', 'Let the model repair itself'], answer: 1, why: 'Different intents with different required parameters need separate schemas.' },
  { q: 'An external API returns a temporary 503. Where should recovery happen?', options: ['The agent retries every turn', 'The tool retries with exponential backoff', 'Escalate immediately', 'Convert it to a permission error'], answer: 1, why: 'Mechanical recovery from transient failure belongs inside the tool.' },
  { q: 'A $500 refund limit must be impossible to bypass. Where should it live?', options: ['User prompt', 'System prompt', 'Backend or tool code', 'Few-shot example'], answer: 2, why: 'A prompt is not a security boundary; policy must be enforced in code.' },
  { q: 'Search and document analysis are completely independent. How can latency be reduced?', options: ['Call them sequentially', 'Issue both task calls in the same response', 'Use one agent for everything', 'Summarize first'], answer: 1, why: 'Independent work should run in parallel and fan in.' },
  { q: 'A user changes their budget, but the model keeps using the old value. What is the strongest fix?', options: ['Delete history', 'Increase context', 'Maintain a current-preferences object', 'Tell the model to pay more attention'], answer: 2, why: 'Structured current state removes ambiguity between old and new statements.' },
  { q: 'A frustrated customer has a clear issue the agent can solve immediately. What is the best response?', options: ['Escalate without asking', 'Argue with the customer', 'Offer to solve it now while preserving the escalation option', 'Ask them to repeat everything'], answer: 2, why: 'Optimize first-contact resolution while respecting the user’s escalation choice.' },
  { q: 'A review prompt reports only certain bugs, giving high precision but missing issues. What should change?', options: ['Make the prompt longer', 'Run broad discovery, then apply a separate threshold', 'Only run lint', 'Remove confidence'], answer: 1, why: 'Separate recall-oriented discovery from noise-control filtering.' },
  { q: 'What determines whether the Batch API fits CI review?', options: ['Model size', 'Whether feedback delayed up to 24 hours remains actionable', 'Repository file count', 'Whether JSON is used'], answer: 1, why: 'Batch suitability is an SLA decision before it is a cost decision.' },
]

export const examPatternsEn = [['Missing structure', 'Schema / tool use'], ['Missing real information', 'null / retrieve / review'], ['Transient failure', 'Retry inside the tool'], ['Permanent failure', 'Actionable metadata'], ['Independent work', 'Run in parallel'], ['Dependent work', 'Prompt chaining'], ['Guidance', 'Prompt'], ['Guarantee', 'Backend / hook / orchestrator']]

export const englishSectionMarkers = {
  'agent-loop': ['## 1.', '## 2.'], 'code-exploration': ['## 2.', '### 2.3.'], workflow: ['### 2.3.', '### 3.2.'], context: ['### 3.2.', '## 4.'],
  extraction: ['## 4.', '## 5.'], 'tool-design': ['## 5.', '## 6.'], errors: ['## 6.', '## 7.'], safety: ['## 7.', '## 8.'],
  'multi-agent': ['## 8.', '## 9.'], conversation: ['## 9.', '## 11.'], quality: ['## 11.', '## 12.'], cost: ['## 12.', '## 13.'],
}

export function localizedChapters(chapters, lang) {
  return lang === 'en' ? chapters.map((chapter) => ({ ...chapter, ...chapterEn[chapter.id], questions: chapter.questions.replaceAll('Câu', 'Q') })) : chapters
}
