name: docker-first

services:
  web:
    container_name: docker-first-web
    image: deep-docker/first-web:dev
    build:
      context: .
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
