apiVersion: v1
kind: Service
metadata:
  name: visits-api
  labels:
    app.kubernetes.io/name: visits-api
    app.kubernetes.io/part-of: container-deep-dive
spec:
  selector:
    app.kubernetes.io/name: visits-api
  ports:
    - name: http
      port: 80
      targetPort: http

