apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: container-lab
resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccounts.yaml
  - api-service.yaml
  - api-deployment.yaml
  - db-service.yaml
  - db-statefulset.yaml
