apiVersion: v1
kind: Pod
metadata:
  name: pvc-consumer
  namespace: storage-lab
spec:
  automountServiceAccountToken: false
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: writer
      image: busybox:1.36.1
      command:
        - sh
        - -c
        - 'echo "pod=$(hostname)" >> /data/history; sleep 3600'
      resources:
        requests:
          cpu: 5m
          memory: 4Mi
        limits:
          cpu: 50m
          memory: 16Mi
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: lab-data
